import { Type, type TSchema } from "typebox";
const stringEnum = (values: readonly string[]) => Type.Union(values.map((value) => Type.Literal(value)));

const app = Type.String({ minLength: 1, maxLength: 200, description: "One exact app name, bundle ID or .app path within the user-configured app-access scope. Never a wildcard." });
const stateId = Type.String({ minLength: 1, maxLength: 80, description: "Single-use stateId from the latest cua_get_app_state or validated action-returned state for this app. If the action returns no new stateId, observe again." });
const index = Type.Integer({ minimum: 0, description: "Element index in that native observation, not an index from another tool or old snapshot." });
const coordinate = Type.Number({ minimum: 0, description: "Coordinate relative to the native screenshot returned by cua_get_app_state." });
const schema = (properties: Record<string, TSchema>) => Type.Object(properties, { additionalProperties: false });
export interface NativeSpec { name: string; method: string; description: string; readOnly: boolean; parameters: TSchema }
export const nativeSpecs: NativeSpec[] = [
  { name: "cua_list_apps", method: "list_apps", readOnly: true, parameters: schema({}), description: "List app identities using Codex Sky. No Jev call. Use only when the target app cannot be identified directly." },
  { name: "cua_get_app_state", method: "get_app_state", readOnly: true, parameters: schema({ app, disableDiff: Type.Optional(Type.Boolean()) }), description: "Read native Sky app/window/menu state and screenshot when no current stateId is available. Complete validated action results may return a new stateId, avoiding a duplicate read. Includes diagnostics; task budget is 180s/30 action attempts per agent turn. Text capped at 50 KB/2000 lines. No Jev call; official approval applies." },
  { name: "cua_click", method: "click", readOnly: false, parameters: schema({ app, stateId, element_index: Type.Optional(index), x: Type.Optional(coordinate), y: Type.Optional(coordinate), mouse_button: Type.Optional(stringEnum(["left", "right", "middle"] as const)), click_count: Type.Optional(Type.Integer({ minimum: 1, maximum: 3 })) }), description: "Native click on an observed element OR screenshot coordinate, never both. Main agent must ensure the action is within the user's task. No Jev classification or automatic retry." },
  { name: "cua_drag", method: "drag", readOnly: false, parameters: schema({ app, stateId, from_x: coordinate, from_y: coordinate, to_x: coordinate, to_y: coordinate }), description: "Native drag between points on the current returned screenshot. Requires a fresh observed state and user-authorized task." },
  { name: "cua_perform_secondary_action", method: "perform_secondary_action", readOnly: false, parameters: schema({ app, stateId, element_index: index, action: Type.String({ minLength: 1, maxLength: 200 }) }), description: "Invoke an action explicitly shown for a native AX element. Do not invent an action or use it to bypass confirmation/security warnings." },
  { name: "cua_press_key", method: "press_key", readOnly: false, parameters: schema({ app, stateId, key: Type.String({ minLength: 1, maxLength: 120 }) }), description: "Native key/chord such as Return, Tab, Super_L+l, or Control_L+a in an observed app. Main agent is responsible for task scope and confirmation of consequential actions." },
  { name: "cua_scroll", method: "scroll", readOnly: false, parameters: schema({ app, stateId, element_index: index, direction: stringEnum(["up", "down", "left", "right"] as const), pages: Type.Optional(Type.Number({ exclusiveMinimum: 0, maximum: 10 })) }), description: "Scroll an observed AX element in the requested direction. No Jev call." },
  { name: "cua_select_text", method: "select_text", readOnly: false, parameters: schema({ app, stateId, element_index: index, text: Type.String({ minLength: 1, maxLength: 10000 }), prefix: Type.Optional(Type.String({ maxLength: 2000 })), suffix: Type.Optional(Type.String({ maxLength: 2000 })), selection_type: Type.Optional(stringEnum(["text", "cursor_before", "cursor_after"] as const)) }), description: "Select literal text or place a cursor in an observed native editable element. Never use this to expose protected credentials." },
  { name: "cua_set_value", method: "set_value", readOnly: false, parameters: schema({ app, stateId, element_index: index, value: Type.String({ maxLength: 10000 }) }), description: "Set an observed element value through native Sky. Scope must match the user request. Setting a search field may submit automatically." },
  { name: "cua_type_text", method: "type_text", readOnly: false, parameters: schema({ app, stateId, text: Type.String({ minLength: 1, maxLength: 10000 }) }), description: "Type literal text into the current focus of an observed app via native Sky. Verify focus first; no implicit Return." },
];
export const nativeToolNames = nativeSpecs.map((spec) => spec.name);
export const nativeActionNames = nativeSpecs.filter((spec) => !spec.readOnly).map((spec) => spec.name);
